### PR TITLE
Make dark scroll bar in dark theme

### PR DESCRIPTION
**Pull request by rakleed**

### CODE REVIEW

**Comment by rakleed** [comment]
@tvinzz @slavaleleka @vozersky @ameshkov

**Comment by Versty** [comment]
@rakleed Hi! 
Thanks for your pull request, we are planing to implement a dark scroll bar in the next version.

**Comment by rakleed** [comment]
@Versty in version 1.11.7 the problem is still relevant.

And why can't you just accept my PR?

**Comment by vozersky** [comment]
@rakleed We can and we will, this task is going to be the part of v1.11.8. Thanks!

**Pull request closed without merging**
